---
- name: create create_empty_file
  hosts: iass
  become: yes
  roles:
   - create_empty_file

- name: fetch_linux_distro
  hosts: all
  become: yes
  roles:
   - fetch_linux_distro

  tasks:
  - name: print hostname vs distribution version
    debug:
     msg: Host {{ inventory_hostname }} has a Linux {{ ansible_distribution }} version {{ ansible_distribution_version }}